name: 'TEST Deploy to Cloud Run'

on:
  push:
    branches:
      - "**"

jobs:

  deploy-dev:
    name: deploy to dev

    permissions:
      contents: read
      deployments: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.environment || github.event_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    environment: dev

    env:
      GCR_SERVICE: ${{ vars.GCR_SERVICE }}
      GCR_REGION: ${{ vars.GCR_REGION }}
      GAR_PATH: ${{ vars.GAR_PATH }}
      IMAGE_NAME: bcr-court-test

    steps:

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d # v3
        with:
          service:  ${{ env.GCR_SERVICE }}
          region:   ${{ env.GCR_REGION }}
          image:    ${{ env.GAR_PATH }}/${{ env.IMAGE_NAME }}:latest